name: CI

on: [ push, pull_request ]

jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install dependencies
      run: sudo apt update && sudo apt install libglu1-mesa-dev libncurses-dev
    - name: Calculate Version
      run: .ci/calculate_version.sh
    - name: Bootstrap compiler
      run: .ci/bootstrap.sh lnx
    - name: Compile
      run: .ci/compile.sh
    - name: Print QB64 Version
      run: ./qb64 -?
    - name: Create QB64 tar.gz
      run: .ci/deploy.sh lnx
    - uses: actions/upload-artifact@v3
      with:
        name: qb64-linux
        path: qb64_lnx.tar.gz

  macos-build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Calculate Version
      run: .ci/calculate_version.sh
    - name: Bootstrap compiler
      run: .ci/bootstrap.sh osx
    - name: Compile
      run: .ci/compile.sh
    - name: Print QB64 Version
      run: ./qb64 -?
    - name: Create QB64 tar.gz
      run: .ci/deploy.sh osx
    - uses: actions/upload-artifact@v3
      with:
        name: qb64-osx
        path: qb64_osx.tar.gz

  windows-x86-build:
    runs-on: windows-latest
    env:
      PLATFORM: x86
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Calculate Version
      shell: bash
      run: .ci/calculate_version.sh
    - name: Bootstrap compiler
      run: .ci/bootstrap.bat
    - name: Compile
      run: .ci/compile.bat
    - name: Print QB64 Version
      run: ./qb64 -?
    - name: Create QB64 7z
      run: .ci/deploy.ps1
    - uses: actions/upload-artifact@v3
      with:
        name: qb64-win-x86
        path: qb64_win-x86.7z

  windows-x64-build:
    runs-on: windows-latest
    env:
      PLATFORM: x64
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Calculate Version
      shell: bash
      run: .ci/calculate_version.sh
    - name: Bootstrap compiler
      run: .ci/bootstrap.bat
    - name: Compile
      run: .ci/compile.bat
    - name: Print QB64 Version
      run: ./qb64 -?
    - name: Create QB64 7z
      run: .ci/deploy.ps1
    - uses: actions/upload-artifact@v3
      with:
        name: qb64-win-x64
        path: qb64_win-x64.7z
